//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.05 at 09:06:28 AM AST 
//


package sa.tabadul.useraccessmanagement.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BranchStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BranchStructure"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Serial" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="CRNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BranchLicenseNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CityName" type="{http://yefi.gov.sa/CommonTypes/xml/schemas/version2.0}CityStructure" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BranchStructure", namespace = "http://yefi.gov.sa/DZIT/ZakatCertificate/xml/schemas/version/3.0", propOrder = {
    "name",
    "serial",
    "crNumber",
    "branchLicenseNo",
    "cityName"
})
public class BranchStructure {

    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Serial")
    protected int serial;
    @XmlElement(name = "CRNumber")
    protected String crNumber;
    @XmlElement(name = "BranchLicenseNo")
    protected String branchLicenseNo;
    @XmlElement(name = "CityName")
    protected CityStructure cityName;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the serial property.
     * 
     */
    public int getSerial() {
        return serial;
    }

    /**
     * Sets the value of the serial property.
     * 
     */
    public void setSerial(int value) {
        this.serial = value;
    }

    /**
     * Gets the value of the crNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCRNumber() {
        return crNumber;
    }

    /**
     * Sets the value of the crNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCRNumber(String value) {
        this.crNumber = value;
    }

    /**
     * Gets the value of the branchLicenseNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranchLicenseNo() {
        return branchLicenseNo;
    }

    /**
     * Sets the value of the branchLicenseNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranchLicenseNo(String value) {
        this.branchLicenseNo = value;
    }

    /**
     * Gets the value of the cityName property.
     * 
     * @return
     *     possible object is
     *     {@link CityStructure }
     *     
     */
    public CityStructure getCityName() {
        return cityName;
    }

    /**
     * Sets the value of the cityName property.
     * 
     * @param value
     *     allowed object is
     *     {@link CityStructure }
     *     
     */
    public void setCityName(CityStructure value) {
        this.cityName = value;
    }

}
