//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.05 at 09:06:28 AM AST 
//


package sa.tabadul.useraccessmanagement.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CityStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CityStructure"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="CityCode" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *           &lt;element name="CityString" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CityStructure", namespace = "http://yefi.gov.sa/CommonTypes/xml/schemas/version2.0", propOrder = {
    "cityCode",
    "cityString"
})
public class CityStructure {

    @XmlElement(name = "CityCode")
    protected Integer cityCode;
    @XmlElement(name = "CityString")
    protected String cityString;

    /**
     * Gets the value of the cityCode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCityCode() {
        return cityCode;
    }

    /**
     * Sets the value of the cityCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCityCode(Integer value) {
        this.cityCode = value;
    }

    /**
     * Gets the value of the cityString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCityString() {
        return cityString;
    }

    /**
     * Sets the value of the cityString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCityString(String value) {
        this.cityString = value;
    }

}
