//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.05 at 09:06:28 AM AST 
//


package sa.tabadul.useraccessmanagement.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getZakatCertificateByCommercialRegistrationNumberForMainBranchOrSubBranchesResponseObject complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getZakatCertificateByCommercialRegistrationNumberForMainBranchOrSubBranchesResponseObject"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{http://yefi.gov.sa/DZIT/ZakatCertificate/xml/schemas/version/3.0}ZakatCertificate" minOccurs="0"/&gt;
 *           &lt;element ref="{http://yefi.gov.sa/YEFIErrorStructure/xml/schemas/version2.3}ServiceError" minOccurs="0"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getZakatCertificateByCommercialRegistrationNumberForMainBranchOrSubBranchesResponseObject", namespace = "http://yesser.gov.sa/DZIT/ZakatCertificateService/version/3.0", propOrder = {
    "zakatCertificate",
    "serviceError"
})
public class GetZakatCertificateByCrNumberResponseObject {

    @XmlElement(name = "ZakatCertificate", namespace = "http://yefi.gov.sa/DZIT/ZakatCertificate/xml/schemas/version/3.0")
    protected ZakatCertificateStructure zakatCertificate;
    @XmlElement(name = "ServiceError", namespace = "http://yefi.gov.sa/YEFIErrorStructure/xml/schemas/version2.3")
    protected CommonErrorStructure serviceError;

    /**
     * Gets the value of the zakatCertificate property.
     * 
     * @return
     *     possible object is
     *     {@link ZakatCertificateStructure }
     *     
     */
    public ZakatCertificateStructure getZakatCertificate() {
        return zakatCertificate;
    }

    /**
     * Sets the value of the zakatCertificate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZakatCertificateStructure }
     *     
     */
    public void setZakatCertificate(ZakatCertificateStructure value) {
        this.zakatCertificate = value;
    }

    /**
     * Gets the value of the serviceError property.
     * 
     * @return
     *     possible object is
     *     {@link CommonErrorStructure }
     *     
     */
    public CommonErrorStructure getServiceError() {
        return serviceError;
    }

    /**
     * Sets the value of the serviceError property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommonErrorStructure }
     *     
     */
    public void setServiceError(CommonErrorStructure value) {
        this.serviceError = value;
    }

}
