//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.05 at 09:06:28 AM AST 
//


package sa.tabadul.useraccessmanagement.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for GHDateStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GHDateStructure"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="GregorianDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="HijriDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GHDateStructure", namespace = "http://yefi.gov.sa/CommonTypes/xml/schemas/version2.0", propOrder = {
    "gregorianDate",
    "hijriDate"
})
public class GHDateStructure {

    @XmlElement(name = "GregorianDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar gregorianDate;
    @XmlElement(name = "HijriDate")
    protected String hijriDate;

    /**
     * Gets the value of the gregorianDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getGregorianDate() {
        return gregorianDate;
    }

    /**
     * Sets the value of the gregorianDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setGregorianDate(XMLGregorianCalendar value) {
        this.gregorianDate = value;
    }

    /**
     * Gets the value of the hijriDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHijriDate() {
        return hijriDate;
    }

    /**
     * Sets the value of the hijriDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHijriDate(String value) {
        this.hijriDate = value;
    }

}
