//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.05 at 09:06:28 AM AST 
//


package sa.tabadul.useraccessmanagement.soap;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ItemChoiceType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ItemChoiceType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="IqamaNumber"/&gt;
 *     &lt;enumeration value="NationalID"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ItemChoiceType", namespace = "http://yefi.gov.sa/PersonProfileCommonTypes/xml/schemas/version2.0")
@XmlEnum
public enum ItemChoiceType {

    @XmlEnumValue("IqamaNumber")
    IQAMA_NUMBER("IqamaNumber"),
    @XmlEnumValue("NationalID")
    NATIONAL_ID("NationalID");
    private final String value;

    ItemChoiceType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ItemChoiceType fromValue(String v) {
        for (ItemChoiceType c: ItemChoiceType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
