//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.05 at 09:06:28 AM AST 
//


package sa.tabadul.useraccessmanagement.soap;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the sa.tabadul.usermanagement.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CommonErrorElement_QNAME = new QName("http://tempuri.org/", "commonErrorElement");
    private final static QName _ZakatCertificate_QNAME = new QName("http://yefi.gov.sa/DZIT/ZakatCertificate/xml/schemas/version/3.0", "ZakatCertificate");
    private final static QName _ServiceError_QNAME = new QName("http://yefi.gov.sa/YEFIErrorStructure/xml/schemas/version2.3", "ServiceError");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: sa.tabadul.usermanagement.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetZakatCertificateBy700CodeforMainBranchOrSubBranches }
     * 
     */
    public GetZakatCertificateBy700CodeforMainBranchOrSubBranches createGetZakatCertificateBy700CodeforMainBranchOrSubBranches() {
        return new GetZakatCertificateBy700CodeforMainBranchOrSubBranches();
    }

    /**
     * Create an instance of {@link GetZakatCertificateBy700CodeforMainBranchOrSubBranchesResponse }
     * 
     */
    public GetZakatCertificateBy700CodeforMainBranchOrSubBranchesResponse createGetZakatCertificateBy700CodeforMainBranchOrSubBranchesResponse() {
        return new GetZakatCertificateBy700CodeforMainBranchOrSubBranchesResponse();
    }

    /**
     * Create an instance of {@link GetZakatCertificateBy700CodeforMainBranchOrSubBranchesResponseObject }
     * 
     */
    public GetZakatCertificateBy700CodeforMainBranchOrSubBranchesResponseObject createGetZakatCertificateBy700CodeforMainBranchOrSubBranchesResponseObject() {
        return new GetZakatCertificateBy700CodeforMainBranchOrSubBranchesResponseObject();
    }

    /**
     * Create an instance of {@link CommonErrorStructure }
     * 
     */
    public CommonErrorStructure createCommonErrorStructure() {
        return new CommonErrorStructure();
    }

    /**
     * Create an instance of {@link GetZakatCertificateByCrNumber }
     * 
     */
    public GetZakatCertificateByCrNumber createGetZakatCertificateByCommercialRegistrationNumberForMainBranchOrSubBranches() {
        return new GetZakatCertificateByCrNumber();
    }

    /**
     * Create an instance of {@link GetZakatCertificateByCrNumberResponse }
     * 
     */
    public GetZakatCertificateByCrNumberResponse createGetZakatCertificateByCommercialRegistrationNumberForMainBranchOrSubBranchesResponse() {
        return new GetZakatCertificateByCrNumberResponse();
    }

    /**
     * Create an instance of {@link GetZakatCertificateByCrNumberResponseObject }
     * 
     */
    public GetZakatCertificateByCrNumberResponseObject createGetZakatCertificateByCommercialRegistrationNumberForMainBranchOrSubBranchesResponseObject() {
        return new GetZakatCertificateByCrNumberResponseObject();
    }

    /**
     * Create an instance of {@link GetZakatCertificateByNationalityIDOrIqamaID }
     * 
     */
    public GetZakatCertificateByNationalityIDOrIqamaID createGetZakatCertificateByNationalityIDOrIqamaID() {
        return new GetZakatCertificateByNationalityIDOrIqamaID();
    }

    /**
     * Create an instance of {@link GetZakatCertificateByNationalityIDOrIqamaIDResponse }
     * 
     */
    public GetZakatCertificateByNationalityIDOrIqamaIDResponse createGetZakatCertificateByNationalityIDOrIqamaIDResponse() {
        return new GetZakatCertificateByNationalityIDOrIqamaIDResponse();
    }

    /**
     * Create an instance of {@link GetZakatCertificateByNationalityIDOrIqamaIDResponseObject }
     * 
     */
    public GetZakatCertificateByNationalityIDOrIqamaIDResponseObject createGetZakatCertificateByNationalityIDOrIqamaIDResponseObject() {
        return new GetZakatCertificateByNationalityIDOrIqamaIDResponseObject();
    }

    /**
     * Create an instance of {@link GetZakatCertificateByTINandCertificatesType }
     * 
     */
    public GetZakatCertificateByTINandCertificatesType createGetZakatCertificateByTINandCertificatesType() {
        return new GetZakatCertificateByTINandCertificatesType();
    }

    /**
     * Create an instance of {@link GetZakatCertificateByTINandCertificatesTypeResponse }
     * 
     */
    public GetZakatCertificateByTINandCertificatesTypeResponse createGetZakatCertificateByTINandCertificatesTypeResponse() {
        return new GetZakatCertificateByTINandCertificatesTypeResponse();
    }

    /**
     * Create an instance of {@link GetZakatCertificateByTINandCertificatesTypeResponseObject }
     * 
     */
    public GetZakatCertificateByTINandCertificatesTypeResponseObject createGetZakatCertificateByTINandCertificatesTypeResponseObject() {
        return new GetZakatCertificateByTINandCertificatesTypeResponseObject();
    }

    /**
     * Create an instance of {@link GetZakatCertificatesByTIN }
     * 
     */
    public GetZakatCertificatesByTIN createGetZakatCertificatesByTIN() {
        return new GetZakatCertificatesByTIN();
    }

    /**
     * Create an instance of {@link GetZakatCertificatesByTINResponse }
     * 
     */
    public GetZakatCertificatesByTINResponse createGetZakatCertificatesByTINResponse() {
        return new GetZakatCertificatesByTINResponse();
    }

    /**
     * Create an instance of {@link GetZakatCertificatesByTINResponseObject }
     * 
     */
    public GetZakatCertificatesByTINResponseObject createGetZakatCertificatesByTINResponseObject() {
        return new GetZakatCertificatesByTINResponseObject();
    }

    /**
     * Create an instance of {@link ZakatCertificateStructure }
     * 
     */
    public ZakatCertificateStructure createZakatCertificateStructure() {
        return new ZakatCertificateStructure();
    }

    /**
     * Create an instance of {@link IdentifierStructure }
     * 
     */
    public IdentifierStructure createIdentifierStructure() {
        return new IdentifierStructure();
    }

    /**
     * Create an instance of {@link ArrayOfBranchStructure }
     * 
     */
    public ArrayOfBranchStructure createArrayOfBranchStructure() {
        return new ArrayOfBranchStructure();
    }

    /**
     * Create an instance of {@link BranchStructure }
     * 
     */
    public BranchStructure createBranchStructure() {
        return new BranchStructure();
    }

    /**
     * Create an instance of {@link GHDateStructure }
     * 
     */
    public GHDateStructure createGHDateStructure() {
        return new GHDateStructure();
    }

    /**
     * Create an instance of {@link CityStructure }
     * 
     */
    public CityStructure createCityStructure() {
        return new CityStructure();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommonErrorStructure }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CommonErrorStructure }{@code >}
     */
    @XmlElementDecl(namespace = "http://tempuri.org/", name = "commonErrorElement")
    public JAXBElement<CommonErrorStructure> createCommonErrorElement(CommonErrorStructure value) {
        return new JAXBElement<CommonErrorStructure>(_CommonErrorElement_QNAME, CommonErrorStructure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ZakatCertificateStructure }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ZakatCertificateStructure }{@code >}
     */
    @XmlElementDecl(namespace = "http://yefi.gov.sa/DZIT/ZakatCertificate/xml/schemas/version/3.0", name = "ZakatCertificate")
    public JAXBElement<ZakatCertificateStructure> createZakatCertificate(ZakatCertificateStructure value) {
        return new JAXBElement<ZakatCertificateStructure>(_ZakatCertificate_QNAME, ZakatCertificateStructure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommonErrorStructure }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CommonErrorStructure }{@code >}
     */
    @XmlElementDecl(namespace = "http://yefi.gov.sa/YEFIErrorStructure/xml/schemas/version2.3", name = "ServiceError")
    public JAXBElement<CommonErrorStructure> createServiceError(CommonErrorStructure value) {
        return new JAXBElement<CommonErrorStructure>(_ServiceError_QNAME, CommonErrorStructure.class, null, value);
    }

}
