//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.05 at 09:06:28 AM AST 
//


package sa.tabadul.useraccessmanagement.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ZakatCertificateStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ZakatCertificateStructure"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TIN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Number" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IssueDate" type="{http://yefi.gov.sa/CommonTypes/xml/schemas/version2.0}GHDateStructure" minOccurs="0"/&gt;
 *         &lt;element name="ExpiryDate" type="{http://yefi.gov.sa/CommonTypes/xml/schemas/version2.0}GHDateStructure" minOccurs="0"/&gt;
 *         &lt;element name="CertificateType" type="{http://yefi.gov.sa/DZIT/ZakatCertificate/xml/schemas/version/3.0}ZakatCertificateType"/&gt;
 *         &lt;element name="Identifier" type="{http://yefi.gov.sa/DZIT/ZakatCertificate/xml/schemas/version/3.0}IdentifierStructure" minOccurs="0"/&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CRNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LicenseNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Branches" type="{http://yefi.gov.sa/DZIT/ZakatCertificate/xml/schemas/version/3.0}ArrayOfBranchStructure" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ZakatCertificateStructure", namespace = "http://yefi.gov.sa/DZIT/ZakatCertificate/xml/schemas/version/3.0", propOrder = {
    "tin",
    "number",
    "issueDate",
    "expiryDate",
    "certificateType",
    "identifier",
    "name",
    "crNumber",
    "licenseNo",
    "branches"
})
public class ZakatCertificateStructure {

    @XmlElement(name = "TIN")
    protected String tin;
    @XmlElement(name = "Number")
    protected String number;
    @XmlElement(name = "IssueDate")
    protected GHDateStructure issueDate;
    @XmlElement(name = "ExpiryDate")
    protected GHDateStructure expiryDate;
    @XmlElement(name = "CertificateType", required = true)
    @XmlSchemaType(name = "string")
    protected ZakatCertificateType certificateType;
    @XmlElement(name = "Identifier")
    protected IdentifierStructure identifier;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "CRNumber")
    protected String crNumber;
    @XmlElement(name = "LicenseNo")
    protected String licenseNo;
    @XmlElement(name = "Branches")
    protected ArrayOfBranchStructure branches;

    /**
     * Gets the value of the tin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIN() {
        return tin;
    }

    /**
     * Sets the value of the tin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIN(String value) {
        this.tin = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the issueDate property.
     * 
     * @return
     *     possible object is
     *     {@link GHDateStructure }
     *     
     */
    public GHDateStructure getIssueDate() {
        return issueDate;
    }

    /**
     * Sets the value of the issueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link GHDateStructure }
     *     
     */
    public void setIssueDate(GHDateStructure value) {
        this.issueDate = value;
    }

    /**
     * Gets the value of the expiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link GHDateStructure }
     *     
     */
    public GHDateStructure getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the value of the expiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link GHDateStructure }
     *     
     */
    public void setExpiryDate(GHDateStructure value) {
        this.expiryDate = value;
    }

    /**
     * Gets the value of the certificateType property.
     * 
     * @return
     *     possible object is
     *     {@link ZakatCertificateType }
     *     
     */
    public ZakatCertificateType getCertificateType() {
        return certificateType;
    }

    /**
     * Sets the value of the certificateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZakatCertificateType }
     *     
     */
    public void setCertificateType(ZakatCertificateType value) {
        this.certificateType = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierStructure }
     *     
     */
    public IdentifierStructure getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierStructure }
     *     
     */
    public void setIdentifier(IdentifierStructure value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the crNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCRNumber() {
        return crNumber;
    }

    /**
     * Sets the value of the crNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCRNumber(String value) {
        this.crNumber = value;
    }

    /**
     * Gets the value of the licenseNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicenseNo() {
        return licenseNo;
    }

    /**
     * Sets the value of the licenseNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicenseNo(String value) {
        this.licenseNo = value;
    }

    /**
     * Gets the value of the branches property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfBranchStructure }
     *     
     */
    public ArrayOfBranchStructure getBranches() {
        return branches;
    }

    /**
     * Sets the value of the branches property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfBranchStructure }
     *     
     */
    public void setBranches(ArrayOfBranchStructure value) {
        this.branches = value;
    }

}
