//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.05 at 09:06:28 AM AST 
//


package sa.tabadul.useraccessmanagement.soap;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ZakatCertificateType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ZakatCertificateType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Registered"/&gt;
 *     &lt;enumeration value="Restricted"/&gt;
 *     &lt;enumeration value="Certified"/&gt;
 *     &lt;enumeration value="Facilities Letter"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ZakatCertificateType", namespace = "http://yefi.gov.sa/DZIT/ZakatCertificate/xml/schemas/version/3.0")
@XmlEnum
public enum ZakatCertificateType {

    @XmlEnumValue("Registered")
    REGISTERED("Registered"),
    @XmlEnumValue("Restricted")
    RESTRICTED("Restricted"),
    @XmlEnumValue("Certified")
    CERTIFIED("Certified"),
    @XmlEnumValue("Facilities Letter")
    FACILITIES_LETTER("Facilities Letter");
    private final String value;

    ZakatCertificateType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ZakatCertificateType fromValue(String v) {
        for (ZakatCertificateType c: ZakatCertificateType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
